// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DragReagon: typeof import('./src/components/DragReagon.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  }
}

export {}
